"use client";
import { useActionState } from "react";
import { LoaderCircle, Save } from "lucide-react";
import { updateAssessmentQuestion } from "@/app/actions/admin-assessment-content";
import type { ContentRow } from "@/lib/assessments/content";
export function AssessmentQuestionEditor({ row, number, scores }: { row: ContentRow; number: number; scores: readonly number[] }) {
  const [state, action, pending] = useActionState(updateAssessmentQuestion, {}); const input = "mt-1.5 w-full rounded-xl border border-line px-3 py-2 text-sm outline-none focus:border-coastal";
  return <form action={action} className="rounded-2xl border border-line bg-white p-5 shadow-card sm:p-7"><input type="hidden" name="assessmentType" value={row.assessment_type} /><input type="hidden" name="questionKey" value={row.question_key} /><div className="flex items-center justify-between gap-4"><h2 className="font-semibold text-navy">{number}. {row.question_key.replaceAll("_", " ")}</h2><span className="rounded-full bg-sky px-3 py-1 text-xs font-semibold text-coastal">Scoring locked</span></div><div className="mt-5 grid gap-4 lg:grid-cols-2"><label className="text-sm font-medium text-ink">Category — English<input required name="categoryEn" defaultValue={row.category_en} className={input} /></label><label className="text-sm font-medium text-ink">分类 — 中文<input required name="categoryZh" defaultValue={row.category_zh} className={input} /></label><label className="text-sm font-medium text-ink">Question — English<textarea required name="questionEn" defaultValue={row.question_en} rows={3} className={input} /></label><label className="text-sm font-medium text-ink">问题 — 中文<textarea required name="questionZh" defaultValue={row.question_zh} rows={3} className={input} /></label></div><div className="mt-5 grid gap-3">{row.option_labels_en.map((label, index) => <div key={index} className="grid gap-3 rounded-xl bg-mist p-3 lg:grid-cols-[75px_1fr_1fr]"><span className="pt-2 text-xs font-semibold text-muted">{scores[index]}/10</span><label className="text-xs font-semibold text-muted">English<input required name={`optionEn${index}`} defaultValue={label} className={input} /></label><label className="text-xs font-semibold text-muted">中文<input required name={`optionZh${index}`} defaultValue={row.option_labels_zh[index]} className={input} /></label></div>)}</div>{state.error && <p className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{state.error}</p>}{state.success && <p className="mt-4 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{state.success}</p>}<button disabled={pending} className="mt-5 inline-flex h-11 items-center gap-2 rounded-xl bg-navy px-5 text-sm font-semibold text-white disabled:opacity-50">{pending ? <LoaderCircle className="size-4 animate-spin" /> : <Save className="size-4" />}Save wording</button></form>;
}
