"use client";
import { useActionState, useState } from "react";
import { ArrowDown, ArrowUp, FilePlus2, GripVertical, ImagePlus, LoaderCircle, Trash2, Type, Video } from "lucide-react";
import { createBlogPost } from "@/app/actions/admin-blog";
type Block={id:string;type:"text"|"image"|"video"};
export function BlogPostForm(){
 const [state,action,pending]=useActionState(createBlogPost,{}),[blocks,setBlocks]=useState<Block[]>([{id:"opening-text",type:"text"}]);
 const add=(type:Block["type"])=>setBlocks(current=>[...current,{id:crypto.randomUUID(),type}]),remove=(id:string)=>setBlocks(current=>current.filter(block=>block.id!==id));
 const move=(index:number,direction:-1|1)=>setBlocks(current=>{const next=[...current],target=index+direction;if(target<0||target>=next.length)return current;[next[index],next[target]]=[next[target],next[index]];return next;});
 const field="w-full border-0 bg-transparent px-0 outline-none placeholder:text-slate-400 focus:ring-0";
 return <form action={action} className="mt-6 grid gap-5"><input type="hidden" name="contentManifest" value={JSON.stringify(blocks)} readOnly/>
  <label className="text-sm font-medium text-ink">Title<input required name="title" maxLength={160} placeholder="Article title" className="mt-2 h-12 w-full rounded-xl border border-line px-4 outline-none focus:border-coastal"/></label>
  <div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium text-ink">Author name<input name="authorName" maxLength={120} placeholder="Leave blank to use your account name" className="mt-2 h-12 w-full rounded-xl border border-line px-4 outline-none focus:border-coastal"/></label><label className="text-sm font-medium text-ink">Publication date and time<input name="publishDateTime" type="datetime-local" className="mt-2 h-12 w-full rounded-xl border border-line px-4 outline-none focus:border-coastal"/><span className="mt-1 block text-xs font-normal text-muted">Brisbane time. Leave blank to use the publishing time.</span></label></div>
  <label className="text-sm font-medium text-ink">Introduction / summary<textarea required name="excerpt" minLength={20} maxLength={1200} rows={5} placeholder="Approximately 200 words introducing the article…" className="mt-2 w-full rounded-xl border border-line px-4 py-3 leading-6 outline-none focus:border-coastal"/><span className="mt-1 block text-xs font-normal text-muted">Shown in the horizontal Blog directory card.</span></label>
  <section className="overflow-hidden rounded-2xl border border-line bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-line bg-mist/70 px-5 py-4"><div><h3 className="font-semibold text-navy">Article content canvas</h3><p className="mt-1 text-xs text-muted">Build one continuous article with consistent publishing spacing.</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>add("text")} className="inline-flex h-9 items-center gap-2 rounded-lg border border-line bg-white px-3 text-xs font-semibold text-navy"><Type className="size-3.5"/>Insert text</button><button type="button" onClick={()=>add("image")} className="inline-flex h-9 items-center gap-2 rounded-lg border border-line bg-white px-3 text-xs font-semibold text-navy"><ImagePlus className="size-3.5"/>Insert image</button><button type="button" onClick={()=>add("video")} className="inline-flex h-9 items-center gap-2 rounded-lg border border-line bg-white px-3 text-xs font-semibold text-navy"><Video className="size-3.5"/>Insert video</button></div></div>
   <div className="divide-y divide-line px-5 sm:px-7">{blocks.map((block,index)=><div key={block.id} className="grid grid-cols-[24px_minmax(0,1fr)] gap-3 py-6"><GripVertical className="mt-2 size-4 text-slate-300"/><div><div className="mb-3 flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-wider text-coastal">{block.type}</p><div className="flex gap-1"><button type="button" onClick={()=>move(index,-1)} disabled={index===0} aria-label="Move content up" className="grid size-8 place-items-center rounded-lg text-muted hover:bg-mist disabled:opacity-25"><ArrowUp className="size-3.5"/></button><button type="button" onClick={()=>move(index,1)} disabled={index===blocks.length-1} aria-label="Move content down" className="grid size-8 place-items-center rounded-lg text-muted hover:bg-mist disabled:opacity-25"><ArrowDown className="size-3.5"/></button><button type="button" onClick={()=>remove(block.id)} disabled={blocks.length===1} aria-label="Delete content" className="grid size-8 place-items-center rounded-lg text-red-600 hover:bg-red-50 disabled:opacity-25"><Trash2 className="size-3.5"/></button></div></div>
    {block.type==="text"&&<textarea required name={`text_${block.id}`} rows={8} placeholder="Write paragraphs here. Insert an image or video whenever the article needs one…" className={`${field} resize-y text-base leading-8 text-ink`}/>} {block.type==="image"&&<div className="grid gap-3 rounded-xl bg-mist/60 p-4"><input required name={`image_${block.id}`} type="file" accept="image/jpeg,image/png,image/webp,image/gif" className="block w-full text-sm text-muted file:mr-4 file:rounded-lg file:border-0 file:bg-navy file:px-4 file:py-2 file:font-semibold file:text-white"/><input name={`caption_${block.id}`} maxLength={240} placeholder="Optional image caption" className="h-10 border-0 border-b border-line bg-transparent px-0 text-sm outline-none focus:border-coastal"/></div>} {block.type==="video"&&<div className="rounded-xl bg-mist/60 p-4"><input required name={`video_${block.id}`} type="url" placeholder="Paste a YouTube, Vimeo or direct MP4 URL" className={`${field} h-10 text-sm`}/></div>}
   </div></div>)}</div><div className="border-t border-line bg-mist/40 px-5 py-3 text-xs text-muted">The canvas order above is the exact order used on the published article.</div></section>
  <label className="flex items-center gap-3 text-sm font-medium text-ink"><input name="published" type="checkbox" className="size-4 accent-[#247fa2]"/>Publish immediately</label>{state.error&&<p role="alert" className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{state.error}</p>}{state.success&&<p role="status" className="rounded-xl bg-sky px-4 py-3 text-sm text-navy">{state.success}</p>}<button disabled={pending} className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-navy px-5 text-sm font-semibold text-white disabled:opacity-50 sm:justify-self-start">{pending?<LoaderCircle className="size-4 animate-spin"/>:<FilePlus2 className="size-4"/>}Add article</button>
 </form>;
}
