import Link from "next/link";
import { ArrowRight, TrendingUp } from "lucide-react";
import { requireStaff } from "@/lib/auth/permissions";
const labels:Record<string,string>={sell_soon:"Planning to sell soon",sell_6_12_months:"Considering 6–12 months",curious_value:"Curious about value",compare_hold_sell:"Comparing hold vs sell",exploring_only:"Exploring options only"};
const priority:Record<string,number>={sell_soon:5,sell_6_12_months:4,compare_hold_sell:3,curious_value:2,exploring_only:1};
export async function PotentialSellerLeads(){
 const {supabase}=await requireStaff(); const {data}=await supabase.from("property_decision_submissions").select("id,user_id,property_id,score,current_thinking,submitted_at,cma_requested_at").order("submitted_at",{ascending:false}).limit(30); if(!data?.length)return null;
 const userIds=[...new Set(data.map(x=>x.user_id))],propertyIds=[...new Set(data.map(x=>x.property_id).filter(Boolean))] as string[];
 const [{data:profiles},{data:properties}]=await Promise.all([supabase.from("profiles").select("id,first_name,last_name,email").in("id",userIds),supabase.from("properties").select("id,address_line_1,suburb").in("id",propertyIds)]);
 const pm=new Map((profiles??[]).map(x=>[x.id,x])),xm=new Map((properties??[]).map(x=>[x.id,x])); const leads=[...data].sort((a,b)=>Number(Boolean(b.cma_requested_at))-Number(Boolean(a.cma_requested_at))||(priority[b.current_thinking]??0)-(priority[a.current_thinking]??0)||Number(b.score)-Number(a.score)).slice(0,10);
 return <section className="mt-8 rounded-2xl border border-line bg-white p-6 shadow-card sm:p-8"><div className="flex items-center gap-3"><TrendingUp className="size-5 text-coastal"/><h2 className="text-xl font-semibold text-navy">Potential Seller Leads</h2></div><div className="mt-5 divide-y divide-line">{leads.map(lead=>{const p=pm.get(lead.user_id),x=lead.property_id?xm.get(lead.property_id):null;return <Link key={lead.id} href={`/admin/property-decision/${lead.id}`} className="grid gap-2 py-4 transition hover:bg-mist sm:grid-cols-[1fr_1fr_auto_auto_auto] sm:items-center sm:gap-5 sm:px-3"><div><p className="font-semibold text-ink">{p?`${p.first_name??""} ${p.last_name??""}`.trim()||"Member":"Member"}</p><p className="text-sm text-muted">{p?.email}</p></div><p className="text-sm text-ink">{x?.suburb||x?.address_line_1||"Property unavailable"}</p><p className="font-semibold text-navy">Score {Number(lead.score)}</p><span className={`justify-self-start rounded-full px-3 py-1 text-xs font-semibold ${lead.cma_requested_at?"bg-emerald-100 text-emerald-800":"bg-sky text-coastal"}`}>{lead.cma_requested_at?"CMA requested":labels[lead.current_thinking]??lead.current_thinking}</span><ArrowRight className="size-4 text-muted"/></Link>})}</div></section>;
}
